### ISSUE TITLE
Encountered an error when integrating Firebase's SDK using Cocoapods

### ISSUE THREAD

**Issue by Kejiasir** [firebase/quickstart-ios#1481]
### pod install

Analyzing dependencies

――― MARKDOWN TEMPLATE ――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.12.0
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]
    RubyGems : 3.0.3.1
        Host : macOS 13.3 (22E252)
       Xcode : 14.3 (14E222b)
         Git : git version 2.39.2 (Apple Git-143)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : bytedance-cocoapods_sdk_source_repo - git - https://github.com/bytedance/cocoapods_sdk_source_repo.git @ cdd6c2e4c0472069826b74790c0a8248dd2da92b

               cocoapods - git - https://github.com/CocoaPods/Specs.git @ b1b5abb17629e2bb4fdfe01108b3b0eda2b3698a

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Crashlytics', '~> 10.5.0'
  pod 'Firebase/Messaging', '~> 10.5.0'
  pod 'Firebase/Analytics', '~> 10.5.0'
  pod 'SnapKit'
  
end
```

### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/arvin/.cocoapods/repos/trunk/Specs/8/b/d/FirebaseCore/10.3.0/FirebaseCore.podspec.json'.

767: unexpected token at '{
  "name": "FirebaseCore",
  "version": "10.3.0",
  "summary": "Firebase Core",
  "description": "Firebase Core includes FIRApp and FIROptions which provide central configuration for other Firebase services.",
  "homepage": "https://firebase.google.com",
  "license": {
    "type": "Apache-2.0",
    "file": "LICENSE"
  },
  "authors": "Google'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/specification.rb:752:in `from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/specification.rb:726:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/source.rb:188:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:348:in `block in delegating_block'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `reverse_each'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `group_possibilities'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:422:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Failed+to+parse+JSON+at+file%3A+%27%2FUsers%2Farvin%2F.cocoapods%2Frepos%2Ftrunk%2FSpecs%2F8%2Fb%2Fd%2FFirebaseCore%2F10.3.0%2FFirebaseCore.podspec.json%27.%0A%0A767%3A+unexpected+token+at+%27%7B%0A++%22name%22%3A+%22FirebaseCore%22%2C%0A++%22version%22%3A+%2210.3.0%22%2C%0A++%22summary%22%3A+%22Firebase+Core%22%2C%0A++%22description%22%3A+%22Firebase+Core+includes+FIRApp+and+FIROptions+which+provide+central+configuration+for+other+Firebase+services.%22%2C%0A++%22homepage%22%3A+%22https%3A%2F%2Ffirebase.google.com%22%2C%0A++%22license%22%3A+%7B%0A++++%22type%22%3A+%22Apache-2.0%22%2C%0A++++%22file%22%3A+%22LICENSE%22%0A++%7D%2C%0A++%22authors%22%3A+%22Google%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

[!] Automatically assigning platform `iOS` with version `16.4` on target `TestDemo` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

――――――――――――――――――――――――――――――――――

When I use Cocoapods to integrate the `Firebase` SDK, the command line outputs the above error message. I try to comment out the integration of Firebase. When integrating other libraries such as`SnapKit`, everything is normal. How should I deal with it? Please help me.

**Comment by paulb777** [comment]
It looks like you're running into a CocoaPods or networking issue.

Your example fails in a different way for me since Firebase 10.x requires at least iOS 11.0. 

The Podfile should be changed to uncomment `# platform :ios, '9.0' and update the version.

**Comment by Kejiasir** [comment]
> 

Thank you for your reply, I found solutions for the same problem online, but most of them didn't work for me, I finally solved it by clearing all cocoapods cache, `sudo rm -rf ~/.cocoapods/repos` and then `pod install`.

**Comment by Lupobb** [comment]
Non parlo inglese
Hai don't Spike Inglis
Sorry

Il sab 15 apr 2023, 16:05 Arvin ***@***.***> ha scritto:
