### ISSUE TITLE
flutter run --verbose fails to launch iOS app

### ISSUE THREAD

**Issue by tmitchmachine** [firebase/quickstart-ios#1626]
Steps to reproduce
manually open Start iOS simulator in VS Code
flutter run --verbose

Source
repo https://github.com/tmitchmachine/genplan

The project bundle identifier name was changed from com.example.genplan to an new name while back.
https://github.com/tmitchmachine/genplan

Newly created Flutter projects work successfully.
The project launches when I run it from Xcode it works.

it always makes it to here and then takes a long time and fails
[ +3 ms] Running Xcode build...
[ +1 ms] executing: [/Users/heavenya/Github/github_genplan/ios/] xcrun xcodebuild
-configuration Debug VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme
Runner BUILD_DIR=/Users/heavenya/Github/github_genplan/build/ios -sdk iphonesimulator
-destination id=7DDD39BE-64EC-4765-97DE-E0D970890B45
SCRIPT_OUTPUT_STREAM_FILE=/var/folders/hw/8n3jpn3d1hzfyc7tt8k44z700000gs/T/flutter_tools.t
tG2R3/flutter_ios_build_temp_dirq9gXhX/pipe_to_stdout -resultBundlePath
/var/folders/hw/8n3jpn3d1hzfyc7tt8k44z700000gs/T/flutter_tools.ttG2R3/flutter_ios_build_te
mp_dirq9gXhX/temporary_xcresult_bundle -resultBundleVersion 3

when I use git checkout to an older versions of the app before adding firebase it worked. I think the problem likely is with firebase or my setup of it anytime I start using an integration of firebase the app stops launching whether it's dragging files over to a fresh project or anything. 
<img width="238" alt="Screenshot 2024-10-14 at 12 25 16 PM" src="https://github.com/user-attachments/assets/1c3d8cab-c096-46b1-ad54-e4ce92d9ca6c">

**Comment by tmitchmachine** [comment]
### Steps to reproduce

manually open Start iOS simulator in VS Code
flutter run --verbose

### Actual results

```console
[  +15 ms] Failed to build iOS app
[   +6 ms] Error (Xcode): Unable to load contents of file list: '/Target Support
           Files/Pods-Runner/Pods-Runner-resources-Debug-input-files.xcfilelist'
           
[   +5 ms] Error (Xcode): Unable to load contents of file list: '/Target Support
           Files/Pods-Runner/Pods-Runner-resources-Debug-output-files.xcfilelist'
           
[        ] Error (Xcode): Unable to load contents of file list: '/Target Support
           Files/Pods-Runner/Pods-Runner-frameworks-Debug-input-files.xcfilelist'
           
[        ] Error (Xcode): Unable to load contents of file list: '/Target Support
           Files/Pods-Runner/Pods-Runner-frameworks-Debug-output-files.xcfilelist'
           
[   +3 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 16 Pro.
[   +5 ms] "flutter run" took 140,711ms.
[  +55 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:874:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
```

### Logs

<details open>
<summary>Logs</summary>

```console
                     ExecuteExternalTool
                     /Applications/Xcode.app/Contents/Developer/usr/bin/actool --version
                     --output-format xml1

                     ExecuteExternalTool
                     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xc
                     toolchain/usr/bin/clang -v -E -dM -arch arm64 -isysroot
                     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.
                     platform/Developer/SDKs/iPhoneSimulator18.0.sdk -x objective-c++ -c
                     /dev/null

                     ExecuteExternalTool
                     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xc
                     toolchain/usr/bin/clang -v -E -dM -arch x86_64 -isysroot
                     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.
                     platform/Developer/SDKs/iPhoneSimulator18.0.sdk -x objective-c++ -c
                     /dev/null

                     Build description signature: f82f3688a5a78df42e202a6057e39c47
                     Build description path:
                     /Users/heavenya/Library/Developer/Xcode/DerivedData/Runner-cnwmtqqwkk
                     mqhohfigzdoumyaase/Build/Intermediates.noindex/XCBuildData/f82f3688a5
                     a78df42e202a6057e39c47.xcbuilddata
                     warning: Run script build phase 'Create Symlinks to Header Folders'
                     will be run during every build because it does not specify any
                     outputs. To address this issue, either add output dependencies to the
                     script phase, or configure it to run in every build by unchecking
                     "Based on dependency analysis" in the script phase. (in target
                     'abseil' from project 'Pods')
                     warning: Run script build phase 'Create Symlinks to Header Folders'
                     will be run during every build because it does not specify any
                     outputs. To address this issue, either add output dependencies to the
                     script phase, or configure it to run in every build by unchecking
                     "Based on dependency analysis" in the script phase. (in target
                     'gRPC-Core' from project 'Pods')
                     warning: Run script build phase 'Create Symlinks to Header Folders'
                     will be run during every build because it does not specify any
                     outputs. To address this issue, either add output dependencies to the
                     script phase, or configure it to run in every build by unchecking
                     "Based on dependency analysis" in the script phase. (in target
                     'BoringSSL-GRPC' from project 'Pods')
                     warning: Unable to read contents of XCFileList '/Target Support
                     Files/Pods-Runner/Pods-Runner-frameworks-Debug-output-files.xcfilelis
                     t' (in target 'Runner' from project 'Runner')
                     warning: Unable to read contents of XCFileList '/Target Support
                     Files/Pods-Runner/Pods-Runner-resources-Debug-output-files.xcfilelist
                     ' (in target 'Runner' from project 'Runner')
                     note: Run script build phase 'Run Script' will be run during every
                     build because the option to run the script phase "Based on dependency
                     analysis" is unchecked. (in target 'Runner' from project 'Runner')
                     note: Run script build phase 'Thin Binary' will be run during every
                     build because the option to run the script phase "Based on dependency
                     analysis" is unchecked. (in target 'Runner' from project 'Runner')
                     error: Unable to load contents of file list: '/Target Support
                     Files/Pods-Runner/Pods-Runner-resources-Debug-input-files.xcfilelist'
                     (in target 'Runner' from project 'Runner')
                     error: Unable to load contents of file list: '/Target Support
                     Files/Pods-Runner/Pods-Runner-resources-Debug-output-files.xcfilelist
                     ' (in target 'Runner' from project 'Runner')
                     error: Unable to load contents of file list: '/Target Support
                     Files/Pods-Runner/Pods-Runner-frameworks-Debug-input-files.xcfilelist
                     ' (in target 'Runner' from project 'Runner')
                     error: Unable to load contents of file list: '/Target Support
                     Files/Pods-Runner/Pods-Runner-frameworks-Debug-output-files.xcfilelis
                     t' (in target 'Runner' from project 'Runner')
                     warning: Run script build phase '[CP] Copy Pods Resources' will be
                     run during every build because it does not specify any outputs. To
                     address this issue, either add output dependencies to the script
                     phase, or configure it to run in every build by unchecking "Based on
                     dependency analysis" in the script phase. (in target 'Runner' from
                     project 'Runner')
                     warning: Run script build phase '[CP] Embed Pods Frameworks' will be
                     run during every build because it does not specify any outputs. To
                     address this issue, either add output dependencies to the script
                     phase, or configure it to run in every build by unchecking "Based on
                     dependency analysis" in the script phase. (in target 'Runner' from
                     project 'Runner')
                     warning: Run script build phase 'Create Symlinks to Header Folders'
                     will be run during every build because it does not specify any
                     outputs. To address this issue, either add output dependencies to the
                     script phase, or configure it to run in every build by unchecking
                     "Based on dependency analysis" in the script phase. (in target
                     'gRPC-C++' from project 'Pods')

                     Result bundle written to path:
                        /var/folders/hw/8n3jpn3d1hzfyc7tt8k44z700000gs/T/flutter_tools.5h28L
                        D/flutter_ios_build_temp_dirSWAYr2/temporary_xcresult_bundle


                     ** BUILD FAILED **


                     The following build commands failed:
                        Building workspace Runner with scheme Runner and configuration Debug
                     (1 failure)
[  +40 ms] Running Xcode build... (completed in 34.7s)
[        ] Xcode build done.                                           34.7s
[  +37 ms] executing: xcrun xcresulttool get --legacy --path
/var/folders/hw/8n3jpn3d1hzfyc7tt8k44z700000gs/T/flutter_tools.5h28LD/flutter_ios_build_te
mp_dirSWAYr2/temporary_xcresult_bundle --format json
[ +164 ms] {
                      "_type" : {
                        "_name" : "ActionsInvocationRecord"
                      },
                      "actions" : {
                        "_type" : {
                          "_name" : "Array"
                        },
                        "_values" : [
                          {
                            "_type" : {
                              "_name" : "ActionRecord"
                            },
                            "actionResult" : {
                              "_type" : {
                                "_name" : "ActionResult"
                              },
                              "coverage" : {
                                "_type" : {
                                  "_name" : "CodeCoverageInfo"
                                }
                              },
                              "issues" : {
                                "_type" : {
                                  "_name" : "ResultIssueSummaries"
                                }
                              },
                              "metrics" : {
                                "_type" : {
                                  "_name" : "ResultMetrics"
                                }
                              },
                              "resultName" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "action"
                              },
                              "status" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "notRequested"
                              }
                            },
                            "buildResult" : {
                              "_type" : {
                                "_name" : "ActionResult"
                              },
                              "coverage" : {
                                "_type" : {
                                  "_name" : "CodeCoverageInfo"
                                }
                              },
                              "issues" : {
                                "_type" : {
                                  "_name" : "ResultIssueSummaries"
                                },
                                "errorSummaries" : {
                                  "_type" : {
                                    "_name" : "Array"
                                  },
                                  "_values" : [
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Error"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Unable to load contents of file list:
                                        '\/Target Support
                                        Files\/Pods-Runner\/Pods-Runner-resources-Debug-in
                                        put-files.xcfilelist'"
                                      }
                                    },
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Error"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Unable to load contents of file list:
                                        '\/Target Support
                                        Files\/Pods-Runner\/Pods-Runner-resources-Debug-ou
                                        tput-files.xcfilelist'"
                                      }
                                    },
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Error"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Unable to load contents of file list:
                                        '\/Target Support
                                        Files\/Pods-Runner\/Pods-Runner-frameworks-Debug-i
                                        nput-files.xcfilelist'"
                                      }
                                    },
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Error"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Unable to load contents of file list:
                                        '\/Target Support
                                        Files\/Pods-Runner\/Pods-Runner-frameworks-Debug-o
                                        utput-files.xcfilelist'"
                                      }
                                    }
                                  ]
                                },
                                "warningSummaries" : {
                                  "_type" : {
                                    "_name" : "Array"
                                  },
                                  "_values" : [
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Warning"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Run script build phase 'Create
                                        Symlinks to Header Folders' will be run during
                                        every build because it does not specify any
                                        outputs. To address this issue, either add output
                                        dependencies to the script phase, or configure it
                                        to run in every build by unchecking \"Based on
                                        dependency analysis\" in the script phase."
                                      }
                                    },
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Warning"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Unable to read contents of XCFileList
                                        '\/Target Support
                                        Files\/Pods-Runner\/Pods-Runner-frameworks-Debug-o
                                        utput-files.xcfilelist'"
                                      }
                                    },
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Warning"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Unable to read contents of XCFileList
                                        '\/Target Support
                                        Files\/Pods-Runner\/Pods-Runner-resources-Debug-ou
                                        tput-files.xcfilelist'"
                                      }
                                    },
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Warning"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Run script build phase '[CP] Copy Pods
                                        Resources' will be run during every build because
                                        it does not specify any outputs. To address this
                                        issue, either add output dependencies to the
                                        script phase, or configure it to run in every
                                        build by unchecking \"Based on dependency
                                        analysis\" in the script phase."
                                      }
                                    },
                                    {
                                      "_type" : {
                                        "_name" : "IssueSummary"
                                      },
                                      "issueType" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Warning"
                                      },
                                      "message" : {
                                        "_type" : {
                                          "_name" : "String"
                                        },
                                        "_value" : "Run script build phase '[CP] Embed
                                        Pods Frameworks' will be run during every build
                                        because it does not specify any outputs. To
                                        address this issue, either add output dependencies
                                        to the script phase, or configure it to run in
                                        every build by unchecking \"Based on dependency
                                        analysis\" in the script phase."
                                      }
                                    }
                                  ]
                                }
                              },
                              "logRef" : {
                                "_type" : {
                                  "_name" : "Reference"
                                },
                                "id" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" :
                                  "0~8ltswYzUYlV61FZwVVa6AZU-G0kP12-jRlw_Gq4eHAZbJxcBquKzt
                                  CrZqz4MRXok0D7Wbnv8Nkqd4CmJJzsiZQ=="
                                },
                                "targetType" : {
                                  "_type" : {
                                    "_name" : "TypeDefinition"
                                  },
                                  "name" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "ActivityLogSection"
                                  }
                                }
                              },
                              "metrics" : {
                                "_type" : {
                                  "_name" : "ResultMetrics"
                                },
                                "errorCount" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "4"
                                },
                                "warningCount" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "5"
                                }
                              },
                              "resultName" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "build"
                              },
                              "status" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "failed"
                              }
                            },
                            "endedTime" : {
                              "_type" : {
                                "_name" : "Date"
                              },
                              "_value" : "2024-10-12T20:29:41.622-0700"
                            },
                            "runDestination" : {
                              "_type" : {
                                "_name" : "ActionRunDestinationRecord"
                              },
                              "displayName" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "iPhone 16 Pro"
                              },
                              "localComputerRecord" : {
                                "_type" : {
                                  "_name" : "ActionDeviceRecord"
                                },
                                "busSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "400"
                                },
                                "cpuCount" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "1"
                                },
                                "cpuKind" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "Quad-Core Intel Core i5"
                                },
                                "cpuSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "2000"
                                },
                                "identifier" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "3F4A886D-37A7-59C7-AD34-C6BD7888FBFD"
                                },
                                "isConcreteDevice" : {
                                  "_type" : {
                                    "_name" : "Bool"
                                  },
                                  "_value" : "true"
                                },
                                "logicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "8"
                                },
                                "modelCode" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "MacBookPro16,2"
                                },
                                "modelName" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "MacBook Pro"
                                },
                                "modelUTI" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" :
                                  "com.apple.macbookpro-13-retina-four-usb-ports-2020"
                                },
                                "name" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "My Mac"
                                },
                                "nativeArchitecture" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "x86_64h"
                                },
                                "operatingSystemVersion" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "15.0.1"
                                },
                                "operatingSystemVersionWithBuildNumber" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "15.0.1 (24A348)"
                                },
                                "physicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "4"
                                },
                                "platformRecord" : {
                                  "_type" : {
                                    "_name" : "ActionPlatformRecord"
                                  },
                                  "identifier" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "com.apple.platform.macosx"
                                  },
                                  "userDescription" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "macOS"
                                  }
                                },
                                "ramSizeInMegabytes" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "16384"
                                }
                              },
                              "targetArchitecture" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "x86_64"
                              },
                              "targetDeviceRecord" : {
                                "_type" : {
                                  "_name" : "ActionDeviceRecord"
                                },
                                "busSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "cpuCount" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "cpuSpeedInMHz" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "identifier" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "7DDD39BE-64EC-4765-97DE-E0D970890B45"
                                },
                                "isConcreteDevice" : {
                                  "_type" : {
                                    "_name" : "Bool"
                                  },
                                  "_value" : "true"
                                },
                                "logicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "modelCode" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iPhone17,1"
                                },
                                "modelName" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iPhone 16 Pro"
                                },
                                "modelUTI" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "com.apple.iphone-16-pro-1"
                                },
                                "name" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iPhone 16 Pro"
                                },
                                "nativeArchitecture" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "x86_64"
                                },
                                "operatingSystemVersion" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "18.0"
                                },
                                "operatingSystemVersionWithBuildNumber" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "18.0 (22A3351)"
                                },
                                "physicalCPUCoresPerPackage" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                },
                                "platformRecord" : {
                                  "_type" : {
                                    "_name" : "ActionPlatformRecord"
                                  },
                                  "identifier" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "com.apple.platform.iphonesimulator"
                                  },
                                  "userDescription" : {
                                    "_type" : {
                                      "_name" : "String"
                                    },
                                    "_value" : "iOS Simulator"
                                  }
                                },
                                "ramSizeInMegabytes" : {
                                  "_type" : {
                                    "_name" : "Int"
                                  },
                                  "_value" : "0"
                                }
                              },
                              "targetSDKRecord" : {
                                "_type" : {
                                  "_name" : "ActionSDKRecord"
                                },
                                "identifier" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "iphonesimulator18.0"
                                },
                                "name" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "Simulator - iOS 18.0"
                                },
                                "operatingSystemVersion" : {
                                  "_type" : {
                                    "_name" : "String"
                                  },
                                  "_value" : "18.0"
                                }
                              }
                            },
                            "schemeCommandName" : {
                              "_type" : {
                                "_name" : "String"
                              },
                              "_value" : "Run"
                            },
                            "schemeTaskName" : {
                              "_type" : {
                                "_name" : "String"
                              },
                              "_value" : "Build"
                            },
                            "startedTime" : {
                              "_type" : {
                                "_name" : "Date"
                              },
                              "_value" : "2024-10-12T20:29:12.311-0700"
                            },
                            "title" : {
                              "_type" : {
                                "_name" : "String"
                              },
                              "_value" : "Build \"Runner\""
                            }
                          }
                        ]
                      },
                      "issues" : {
                        "_type" : {
                          "_name" : "ResultIssueSummaries"
                        },
                        "errorSummaries" : {
                          "_type" : {
                            "_name" : "Array"
                          },
                          "_values" : [
                            {
                              "_type" : {
                                "_name" : "IssueSummary"
                              },
                              "issueType" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Error"
                              },
                              "message" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Unable to load contents of file list:
                                '\/Target Support
                                Files\/Pods-Runner\/Pods-Runner-resources-Debug-input-file
                                s.xcfilelist'"
                              }
                            },
                            {
                              "_type" : {
                                "_name" : "IssueSummary"
                              },
                              "issueType" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Error"
                              },
                              "message" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Unable to load contents of file list:
                                '\/Target Support
                                Files\/Pods-Runner\/Pods-Runner-resources-Debug-output-fil
                                es.xcfilelist'"
                              }
                            },
                            {
                              "_type" : {
                                "_name" : "IssueSummary"
                              },
                              "issueType" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Error"
                              },
                              "message" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Unable to load contents of file list:
                                '\/Target Support
                                Files\/Pods-Runner\/Pods-Runner-frameworks-Debug-input-fil
                                es.xcfilelist'"
                              }
                            },
                            {
                              "_type" : {
                                "_name" : "IssueSummary"
                              },
                              "issueType" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Error"
                              },
                              "message" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Unable to load contents of file list:
                                '\/Target Support
                                Files\/Pods-Runner\/Pods-Runner-frameworks-Debug-output-fi
                                les.xcfilelist'"
                              }
                            }
                          ]
                        },
                        "warningSummaries" : {
                          "_type" : {
                            "_name" : "Array"
                          },
                          "_values" : [
                            {
                              "_type" : {
                                "_name" : "IssueSummary"
                              },
                              "issueType" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Warning"
                              },
                              "message" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Run script build phase 'Create Symlinks to
                                Header Folders' will be run during every build because it
                                does not specify any outputs. To address this issue,
                                either add output dependencies to the script phase, or
                                configure it to run in every build by unchecking \"Based
                                on dependency analysis\" in the script phase."
                              }
                            },
                            {
                              "_type" : {
                                "_name" : "IssueSummary"
                              },
                              "issueType" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Warning"
                              },
                              "message" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Unable to read contents of XCFileList
                                '\/Target Support
                                Files\/Pods-Runner\/Pods-Runner-frameworks-Debug-output-fi
                                les.xcfilelist'"
                              }
                            },
                            {
                              "_type" : {
                                "_name" : "IssueSummary"
                              },
                              "issueType" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Warning"
                              },
                              "message" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Unable to read contents of XCFileList
                                '\/Target Support
                                Files\/Pods-Runner\/Pods-Runner-resources-Debug-output-fil
                                es.xcfilelist'"
                              }
                            },
                            {
                              "_type" : {
                                "_name" : "IssueSummary"
                              },
                              "issueType" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Warning"
                              },
                              "message" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Run script build phase '[CP] Copy Pods
                                Resources' will be run during every build because it does
                                not specify any outputs. To address this issue, either add
                                output dependencies to the script phase, or configure it
                                to run in every build by unchecking \"Based on dependency
                                analysis\" in the script phase."
                              }
                            },
                            {
                              "_type" : {
                                "_name" : "IssueSummary"
                              },
                              "issueType" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Warning"
                              },
                              "message" : {
                                "_type" : {
                                  "_name" : "String"
                                },
                                "_value" : "Run script build phase '[CP] Embed Pods
                                Frameworks' will be run during every build because it does
                                not specify any outputs. To address this issue, either add
                                output dependencies to the script phase, or configure it
                                to run in every build by unchecking \"Based on dependency
                                analysis\" in the script phase."
                              }
                            }
                          ]
                        }
                      },
                      "metadataRef" : {
                        "_type" : {
                          "_name" : "Reference"
                        },
                        "id" : {
                          "_type" : {
                            "_name" : "String"
                          },
                          "_value" :
                          "0~IFavi2PB5Uo5IdVyakMzcZg_K12qcsivuQNMJJ63sKswkdmgdlEjUScnPCDS8
                          Mu4XQ1crStp1VFO8Az_mhva9g=="
                        },
                        "targetType" : {
                          "_type" : {
                            "_name" : "TypeDefinition"
                          },
                          "name" : {
                            "_type" : {
                              "_name" : "String"
                            },
                            "_value" : "ActionsInvocationMetadata"
                          }
                        }
                      },
                      "metrics" : {
                        "_type" : {
                          "_name" : "ResultMetrics"
                        },
                        "errorCount" : {
                          "_type" : {
                            "_name" : "Int"
                          },
                          "_value" : "4"
                        },
                        "warningCount" : {
                          "_type" : {
                            "_name" : "Int"
                          },
                          "_value" : "5"
                        }
                      }
                    }
[  +15 ms] Failed to build iOS app
[   +6 ms] Error (Xcode): Unable to load contents of file list: '/Target Support
           Files/Pods-Runner/Pods-Runner-resources-Debug-input-files.xcfilelist'
           
[   +5 ms] Error (Xcode): Unable to load contents of file list: '/Target Support
           Files/Pods-Runner/Pods-Runner-resources-Debug-output-files.xcfilelist'
           
[        ] Error (Xcode): Unable to load contents of file list: '/Target Support
           Files/Pods-Runner/Pods-Runner-frameworks-Debug-input-files.xcfilelist'
           
[        ] Error (Xcode): Unable to load contents of file list: '/Target Support
           Files/Pods-Runner/Pods-Runner-frameworks-Debug-output-files.xcfilelist'
           
[   +3 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 16 Pro.
[   +5 ms] "flutter run" took 140,711ms.
[  +55 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:874:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +113 ms] ensureAnalyticsSent: 110ms
[        ] Running 2 shutdown hooks
[  +17 ms] Shutdown hooks complete
[   +8 ms] exiting with code 1

```

</details>


### Flutter Doctor output

<details open>
<summary>Doctor output</summary>

```console

heavenya@Travis-Mitchell-MacBook-Pro genplan % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.94.2)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by no-chili** [comment]
same issue，Have you found a  solution?
@tmitchmachine 
```
Launching lib/main.dart on iPhone 12 in debug mode...
Xcode build done.                                           43.6s
Failed to build iOS app
Error (Xcode): Undefined symbols:

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 12.

Exited (1).
```

**Comment by tmitchmachine** [comment]
I worked with hammadalive7 to fix it. If you look at the last 2 commits you will see the changes that were made to the repo that enabled it to work again https://github.com/tmitchmachine/genplan
