### ISSUE TITLE
Analytics LogEvent fails on Sony Xperia Z

### ISSUE THREAD

**Issue by myflashlab** [firebase/quickstart-ios#69]
The very same app works on all our devices except for the Sony Xperia Z. The logcat says:

```
W/WindowManager: Force-removing child win Window{3eda4075 u0 SurfaceView} from container Window{1812555f u0 air.com.doitflash.firebaseCore/air.com.doitflash.firebaseCore.AppEntry}
E/Sensors: HAL:write 14 to fd 277 returned 'Device or resource busy' (16)
E/Sensors: HAL:ACCEL update delay error
W/WindowManager: Failed looking up window
       java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@3c4b7bac does not exist
       at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8742)
       at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8733)
       at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1163)
       at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
I/WindowState: WIN DEATH: null
```

the key part is ```HAL:write 14 to fd 277 returned 'Device or resource busy' (16)``` I think. Any explanation for this?

**Comment by samtstern** [comment]
@myflashlab looks like this is an Android issue, would you mind re-filing it on the [quickstart-android](/firebase/quickstart-android) repo?
